# Generated by Django 2.1.13 on 2019-11-13 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tblhgs',
            fields=[
                ('tckimlikno', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('ad', models.CharField(blank=True, max_length=50, null=True)),
                ('soyad', models.CharField(blank=True, max_length=50, null=True)),
                ('bakiye', models.CharField(blank=True, max_length=50, null=True)),
                ('hgsno', models.CharField(blank=True, max_length=11, null=True)),
            ],
            options={
                'db_table': 'Tblhgs',
                'managed': False,
            },
        ),
    ]
